# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: ''
    weight: 10
    identifier: Reprex
  - name: About Reprex
    url: ../author/reprex/
    weight: 11
    parent: Reprex
  - name: About Our Observatories
    url: ../about/observatories
    weight: 12
    parent: Reprex
  - name: Accomplishments
    url: '#accomplishments'
    weight: 12
    parent: Reprex
#  - name: Tour
#    url: tour
#    weight: 10
  - name: News
    url: post
    weight: 20
    name: Blog
  - name: News
    url: post
    weight: 21
    parent: Blog
  - name: Our Topics
    url: /#tags
    weight: 22
    parent: Blog
  - name: Solutions
    url: '#services'
    weight: 30
    identifier: Solutions
  - name: Apps
    url: '#apps'
    weight: 31
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 32
    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 34
    parent: Solutions
  - name: Data Sharing Spaces
    url: ""
    weight: 40
    identifier: Data
  - name: Overview
    url: '#observatories'
    weight: 40
    parent: Data
  - name: Open Music Observatory &#128279;
    url: 'https://music.dataobservatory.eu'
    weight: 41
    parent: Data
  - name: TextileBase &#128279;
    url: /observatories/textilebase/
    weight: 42
    parent: Data
  - name: Finno-Ugric Data Sharing Space &#128279;
    url: 'https://greendeal.dataobservatory.eu'
    weight: 43
    parent: Data
  - name: Publications
    url: publication
    weight: 80
  - name: Publications
    url: '#featured'
    weight: 70
    identifier: Publications
  - name: Blog
    url: /post/
    weight: 71
    parent: Publications
  - name: Featured
    url: '#featured'
    weight: 72
    parent: Publications
  - name: All Publications
    url: publication
    weight: 73
    parent: Publications
  - name: Contact & Events
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '/contact'
    weight: 90
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact
